### ISSUE TITLE
Is it the expected output?

### ISSUE THREAD

**Issue by rejectozaur** [nvreynolds/refract#2]
Hi, Im testing your gem and the generated output resembles nothing like page objects. I'm kinda missing some documentation. Could you please provide explanation and maybe some snippet how does it work on your side?

```
[2] pry(main)> Refract.create('www.twitter.com')
NoMethodError: undefined method `+' for nil:NilClass
from /Users/name/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:1561:in `addr_port'
[3] pry(main)> Refract.create('https://twitter.com')
page object not created for https://twitter.com/i/directory/profiles
page object not created for https://twitter.com/settings/personalization
page object not created for https://twitter.com/account/complete
^CInterrupt:
from /Users/name/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/protocol.rb:158:in `wait_readable'
[4] pry(main)> Refract.create('https://google.com')
=> #<Spidr::Agent:0x007f8564a4f150
 @authorized=#<Spidr::AuthStore: {}>,
 @cookies=#<Spidr::CookieJar: {}>,
 @default_headers={},
 @delay=0,
 @every_failed_url_blocks=[],
 @every_link_blocks=[],
 @every_page_blocks=[#<Proc:0x007f8564a4e6b0@/Users/name/.rvm/gems/ruby-2.3.0/gems/spidr-0.6.0/lib/spidr/agent/events.rb:232>],
 @every_url_blocks=[],
 @every_url_like_blocks={},
 @ext_rules=#<Spidr::Rules:0x007f8564a4e8b8 @accept=[], @reject=[]>,
 @failures=#<Set: {}>,
 @history=#<Set: {#<URI::HTTPS https://google.com>}>,
 @host_header=nil,
 @host_headers={},
 @host_rules=#<Spidr::Rules:0x007f8564a4eb38 @accept=["google.com"], @reject=[]>,
 @levels={#<URI::HTTPS https://google.com>=>0},
 @limit=nil,
 @link_rules=#<Spidr::Rules:0x007f8564a4e9f8 @accept=[], @reject=[]>,
 @max_depth=nil,
 @paused=false,
 @port_rules=#<Spidr::Rules:0x007f8564a4ea98 @accept=[], @reject=[]>,
 @queue=[],
 @referer=nil,
 @running=false,
 @schemes=["http", "https"],
 @sessions=
  #<Spidr::SessionCache:0x007f8564a4f0d8
   @continue_timeout=nil,
   @keep_alive_timeout=nil,
   @open_timeout=nil,
   @proxy=#<struct Spidr::Proxy host=nil, port=8080, user=nil, password=nil>,
   @read_timeout=nil,
   @sessions={},
   @ssl_timeout=nil>
```

**Comment by nvreynolds** [comment]
Did you figure it out?

**Comment by nvreynolds** [comment]
I didn't put alot of error handling in. Just enough to serve my purposes. But I can help troubleshoot if you'd like.
